INSERT INTO words (word_ja, word_en) VALUES 
('あなたのもの', 'yours'),
('彼女のもの', 'hers'),
('それの', 'its'),
('彼らの、それらの', 'their'),
('彼らを、それらを', 'them'),
('彼らのもの、それらのもの', 'theirs'),
('私たちの', 'our'),
('私たちを', 'we'),
('私たちのもの', 'our'),
('何色', 'what color'),
('何の科目', 'any subject'),
('何時', 'what time'),
('今日は何曜日？', 'what day is it today?'),
('今日の日付は？', 'what is the date today?'),
('あなたの好きな～はなんですか？', 'what is your favorite?'),
('どこ', 'where'),
('誰の', 'whose'),
('どちらの', 'which'),
('どうやって', 'how'),
('どうやって～へ行きますか？', 'how do you go to?'),
('元気ですか？', 'how are you?'),
('いくら', 'how much'),
('いくつ', 'how many'),
('～はどうですか？', 'how about?'),
('分', 'part'),
('時間', 'time'),
('月', 'month'),
('深夜', 'midnight'),
('誕生日', 'birthday'),
('火曜日', 'tuesday'),
('水曜日', 'wednesday'),
('木曜日', 'thursday'),
('金曜日', 'friday'),
('土曜日', 'saturday'),
('1月', 'january'),
('2月', 'february'),
('3月', 'march'),
('4月', 'april'),
('5月', 'in may'),
('6月', 'june'),
('7月', 'july'),
('8月', 'august'),
('9月', 'september'),
('10月', 'october'),
('11月', 'november'),
('12月', 'december'),
('夏', 'summer'),
('秋', 'autumn'),
('秋', 'autumn'),
('カナダ', 'canada'),
('オーストラリア', 'australia'),
('スペイン', 'spain'),
('中国', 'china'),
('フランス', 'france'),
('ドイツ', 'germany'),
('ブラジル', 'brazil'),
('国', 'country'),
('アフリカ', 'africa'),
('ヨーロッパ', 'europe'),
('場所', 'place'),
('駅', 'station'),
('空港', 'airport'),
('公園', 'park'),
('市役所', 'city hall'),
('病院', 'hospital'),
('郵便局', 'post office'),
('店', 'shop'),
('スーパー', 'supermarket'),
('山', 'mountain'),
('レストラン', 'restaurant'),
('寝室', 'bedroom'),
('キッチン/台所', 'kitchen'),
('（トイレつきの）お風呂', 'bath'),
('教室', 'classroom'),
('体育館', 'gym'),
('晴れている', 'sunny'),
('曇っている', 'it is cloudy'),
('雨が降っている', 'it\'s raining'),
('雪が降っている', 'it\'s snowing'),
('霧がかっている', 'foggy'),
('晴天', 'sunshine'),
('太陽', 'sun'),
('雲', 'cloud'),
('雨/雨が降る', 'rain'),
('雨/にわか雨', 'shower'),
('雪/雪が降る', 'snow'),
('霧', 'fog'),
('晴れる', 'clear'),
('ダンサー/おどる人', 'dancer'),
('運転手', 'driver'),
('医者/博士', 'doctor/dr.'),
('友だち', 'friend'),
('少女/女の子', 'girl'),
('仕事/職', 'job'),
('警官/役人', 'police'),
('親', 'parent'),
('兄弟', 'brother'),
('おじいさん', 'old man'),
('おばあさん', 'grandmother'),
('いとこ', 'cousin'),
('人', 'man'),
('人々', 'people'),
('ピアニスト', 'pianist'),
('パイロット', 'pilot'),
('競技者/演奏者', 'players'),
('ウエーター', 'water'),
('働く人', 'worker'),
('バスケットボール', 'basketball'),
('テニス', 'tennis'),
('野球', 'baseball'),
('サッカー', 'soccer'),
('バドミントン', 'badminton'),
('卓球', 'table tennis'),
('サーフィン', 'surfing'),
('水泳', 'swimming'),
('マラソン', 'marathon'),
('ボクシング', 'boxing'),
('夕食/ディナー', 'dinner'),
('月(ひとつき)', 'month'),
('色', 'colour'),
('花', 'flower'),
('果物', 'fruit'),
('辞書', 'dictionary'),
('パスポート', 'passport'),
('腕時計', 'watch'),
('黒板', 'blackboard'),
('カレンダー', 'calendar'),
('靴', 'shoes'),
('傘', 'umbrella'),
('新聞', 'newspaper'),
('髪', 'hair'),
('日記', 'diary'),
('手紙', 'letter'),
('壁', 'wall'),
('鳥', 'bird'),
('人形', 'doll'),
('ぶどう', 'grape'),
('カメラ', 'camera'),
('口', 'mouth'),
('硬貨', 'coin'),
('音楽', 'music'),
('考え/意見', 'idea'),
('クラブ/部', 'club'),
('数/番号', 'number'),
('歴史', 'history'),
('物語/話', 'story'),
('科目', 'subject'),
('飛行機', 'plane'),
('皿', 'plate'),
('木', 'wood'),
('（テレビなど）見る', 'look'),
('～が欲しい', 'want'),
('～をつくる', 'create'),
('勉強する', 'study'),
('～を持つ/手に入れる', 'get'),
('～をとる', 'take'),
('～を書く', 'write'),
('～を使う', 'use'),
('～を洗う', 'wash'),
('～を話す', 'talk'),
('聴く', 'listen'),
('見る', 'look'),
('～を知る', 'know'),
('歩く', 'walk'),
('スキーをする', 'ski'),
('始める', 'start'),
('話す', 'talk'),
('教える', 'teach'),
('～する/～を行う', 'do'),
('考える', 'think'),
('～が欲しい', 'want'),
('～を閉める', 'close'),
('～をあげる・与える', 'give'),
('ダンスする', 'dance'),
('立つ', 'stand'),
('待つ', 'wait'),
('～を置く', 'put'),
('ブラシをかける', 'brush'),
('乗る', 'ride'),
('キャンプをする', 'camp'),
('～を習う/学ぶ', 'learn'),
('にっこりする/笑う', 'smile'),
('始める', 'start'),
('練習する', 'practice'),
('～を運転する', 'drive'),
('お願いする', 'please'),
('～を言う', 'tell'),
('とどまる・いる', 'stay'),
('動く', 'move'),
('回る/（角で）曲がる', 'turn'),
('～を訪ねる/会いに行く', 'visit'),
('～をやってみる/試す', 'try');
